export {
  scanRepository,
  SOURCE_TYPES,
  type RepositoryFile,
  type RepositoryInventory,
  type SourceExtension,
  type SourceType,
} from "./repository-scanner.js";

export {
  analyzeSources,
  type ClassAnalysis,
  type ExportAnalysis,
  type FailedSourceAnalysis,
  type FunctionAnalysis,
  type ImportAnalysis,
  type JsxElementAnalysis,
  type NamedImport,
  type ParseError,
  type SourceAnalysisManifest,
  type SourceFileAnalysis,
  type SourceLocation,
  type SuccessfulSourceAnalysis,
} from "./source-analyzer.js";

export {
  analyzeUiStructure,
  type ComponentExportStatus,
  type DynamicUiProp,
  type StaticPropValueType,
  type StaticUiProp,
  type UiComponent,
  type UiDynamicNode,
  type UiElementNode,
  type UiFragmentNode,
  type UiNode,
  type UiProp,
  type UiStructureManifest,
  type UiTextNode,
} from "./ui-structure-analyzer.js";

export {
  analyzeActionBindings,
  type ActionBinding,
  type ActionBindingManifest,
  type ActionElementContext,
  type HandlerBinding,
  type ImportedHandlerBinding,
  type InlineHandlerBinding,
  type LocalHandlerBinding,
  type MemberExpressionBinding,
  type UnresolvedHandlerBinding,
} from "./action-binding-analyzer.js";

export {
  analyzeRoutesAndNavigation,
  type DynamicRouteValue,
  type NavigationAncestor,
  type NavigationRecord,
  type RouteNavigationManifest,
  type RouteRecord,
  type RouteSource,
  type RouteValue,
  type StaticRouteValue,
} from "./route-navigation-analyzer.js";

export {
  analyzeFunctionCalls,
  createCallableId,
  type CallableKind,
  type CallableRecord,
  type CallBinding,
  type FunctionCall,
  type FunctionCallManifest,
  type ImportedCallBinding,
  type LocalCallBinding,
  type MemberCallBinding,
  type UnresolvedCallBinding,
} from "./function-call-analyzer.js";

export {
  analyzeHttpRequests,
  type DynamicHttpValue,
  type HttpCaller,
  type HttpClientEvidence,
  type HttpHeader,
  type HttpHeaders,
  type HttpRequest,
  type HttpRequestManifest,
  type HttpValue,
  type StaticHttpValue,
} from "./http-request-analyzer.js";

export {
  analyzeGraphqlOperations,
  type DynamicGraphqlValue,
  type FailedGraphqlDocument,
  type GraphqlArgument,
  type GraphqlDirective,
  type GraphqlDocument,
  type GraphqlDocumentReference,
  type GraphqlExecution,
  type GraphqlFieldSelection,
  type GraphqlFragment,
  type GraphqlFragmentSpread,
  type GraphqlInlineFragment,
  type GraphqlOperation,
  type GraphqlOperationManifest,
  type GraphqlOperationType,
  type GraphqlParseError,
  type GraphqlSelection,
  type GraphqlTransportEvidence,
  type GraphqlValue,
  type GraphqlVariableDefinition,
  type StaticGraphqlValue,
  type SuccessfulGraphqlDocument,
  type SuppliedGraphqlVariable,
  type SuppliedGraphqlVariables,
} from "./graphql-operation-analyzer.js";

export {
  buildProductEvidenceGraph,
  getEvidenceNode,
  getIncomingEvidenceEdges,
  getOutgoingEvidenceEdges,
  traceEvidence,
  validateProductEvidenceGraph,
  type EvidenceSource,
  type EvidenceStrength,
  type EvidenceTraceStep,
  type GraphEvidence,
  type ProductEvidenceEdge,
  type ProductEvidenceEdgeType,
  type ProductEvidenceGraph,
  type ProductEvidenceGraphInput,
  type ProductEvidenceNode,
  type ProductEvidenceNodeType,
  type UnresolvedRelationship,
} from "./product-evidence-graph.js";

export {
  resolveProjectSymbols,
  type ModuleResolutionEvidence,
  type ProjectModuleRecord,
  type ProjectSymbolResolutionManifest,
  type ResolvedSymbolTarget,
  type SymbolResolution,
  type SymbolResolutionFailureReason,
  type SymbolResolutionKind,
  type SymbolResolutionStrength,
  type SymbolTargetKind,
  type UnresolvedSymbolResolution,
} from "./project-symbol-resolver.js";

export {
  captureRuntimePage,
  DEFAULT_RUNTIME_VIEWPORT,
  RuntimeCaptureError,
  sanitizeRuntimeUrl,
  validateRuntimeUrl,
  type RuntimeBoundingBox,
  type RuntimeBrowserError,
  type RuntimeCandidateSignal,
  type RuntimeCandidateSignalProvenance,
  type RuntimeCandidateSignalType,
  type RuntimeCaptureFailure,
  type RuntimeCaptureFailureClassification,
  type RuntimeCaptureFailureStage,
  type RuntimeCaptureManifest,
  type RuntimeCaptureOptions,
  type RuntimeCaptureIssue,
  type RuntimeCaptureStages,
  type RuntimeCaptureStatus,
  type RuntimeInteractiveElement,
  type RuntimeInteractionCandidate,
  type RuntimeNetworkObservation,
  type RuntimeSelectOption,
  type RuntimeSemanticEvidence,
  type RuntimeStageStatus,
  type RuntimeTextEvidence,
} from "./runtime-capture.js";

export {
  classifyRuntimeProbeTarget,
  probeRuntimeNavigation,
  type RuntimeNavigationProbeOptions,
  type RuntimeNavigationProbeResult,
  type RuntimeProbeInteraction,
  type RuntimeProbeSafety,
  type RuntimeProbeSafetyDecision,
  type RuntimeProbeTarget,
  type RuntimeProbeTargetContext,
  type RuntimeProbeTransition,
} from "./navigation-probe.js";

export {
  DEFAULT_RUNTIME_DISCOVERY_LIMITS,
  discoverRuntimeNavigation,
  fingerprintRuntimeState,
  type RuntimeDiscoveryBranchStopReason,
  type RuntimeDiscoveryLimits,
  type RuntimeDiscoverySummary,
  type RuntimeNavigationDiscoveryGraph,
  type RuntimeNavigationDiscoveryOptions,
  type RuntimeNetworkEvidenceObservation,
  type RuntimeSkippedTarget,
  type RuntimeStateNode,
  type RuntimeTransitionEdge,
} from "./runtime-discovery.js";

export {
  formatReconciliationSummary,
  getAmbiguousEvidence,
  getCorroboratedEvidence,
  getRuntimeOnlyEvidence,
  getStaticOnlyEvidence,
  reconcileProductEvidence,
  validateReconciliationManifest,
  type ReconciledEvidenceResult,
  type ReconciliationCoverage,
  type ReconciliationDomain,
  type ReconciliationDomainSummary,
  type ReconciliationManifest,
  type ReconciliationRuntimeReference,
  type ReconciliationStaticReference,
  type ReconciliationStatus,
  type ReconciliationStrength,
  type ReconcileProductEvidenceInput,
} from "./evidence-reconciliation.js";

export {
  AuthenticationSessionError,
  createAuthenticatedSession,
  type AuthenticationCredentials,
  type AuthenticationFailure,
  type AuthenticationFailureClassification,
  type AuthenticationFailureStage,
  type AuthenticationLocator,
  type AuthenticationRole,
  type AuthenticationSessionManifest,
  type AuthenticationSuccessCondition,
  type CreateAuthenticatedSessionOptions,
} from "./authenticated-session.js";
